repos:
  - repo: local
    hooks:
      - id: alu
        name: alu test
        entry:  verilator --timing -cc src/alu.sv --exe tests/alu_tb.sv
        language: system
        always_run: true
        pass_filenames: false
