repos:
  - repo: local
    hooks:
      - id: alu
        name: alu test
        entry: verilator --timing --clk --build --assert -Wall --trace -cc --exe src/alu.sv tests/alu_tb.sv
        language: system
        always_run: true
        pass_filenames: false
      - id: ctrl
        name: alu test
        entry:  verilator --timing -cc -Wall src/ctrl.sv tests/ctrl_tb.sv
        language: system
        always_run: true
        pass_filenames: false
