repos:
  - repo: local
    hooks:
      - id: alu
        name: alu test
        entry: verilator --timing --clk --build --assert -Wall --trace -cc --exe tests/alu_tb.sv src/alu.sv
        language: system
        always_run: true
        pass_filenames: false

      #      - id: ctrl
      #        name: ctrl test
      #        entry: verilator --timing --clk --build --assert -Wall --trace -cc --exe tests/ctrl_tb.sv src/ctrl.sv  src/alu.sv
      #        language: system
      #        always_run: true
      #        pass_filenames: false
