name: Cpu test

on:
  push:
    branches:
      - '**'  # Run on push events for all branches

jobs:
  test:
    runs-on: ubuntu-latest

    #    strategy:
    #      matrix:
    #        target: [alu, ctrl]
    #        target: [alu, ctrl, rf, ram, cpu]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Verilator Action
      uses: V0XNIHILI/install-verilator-action@v0.0.2

    - name: Test alu
      run: | 
        verilator --timing --clk --build --assert -Wall --trace -cc  --binary --exe src/alu.sv tests/alu_tb.sv && ./obj_dir/Valu

    - name: Test ctrl
      run: | 
        verilator --timing --clk --build --assert -Wall --trace -cc  --binary --exe src/ctrl.sv tests/ctrl_tb.sv && ./obj_dir/Vctrl

      #    - name: Test ${{ matrix.target }}
      #      run: | 
      #        verilator --timing --clk --build --assert -Wall --trace -cc  --binary --exe src/${{ matrix.target }}.sv tests/${{ matrix.target }}_tb.sv && ./obj_dir/V${{ matrix.target }}
