name: Main cpu test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Icarus Verilog
        run: |
          sudo apt-get update
          sudo apt-get install -y iverilog

      - name: ALU
        run: |
          iverilog -o alu -g2005-sv src/alu.sv tests/alu_tb.sv
          vvp alu
          if [ ! -f sim.vcd ]; then 
            exit 1
          fi


      - name: Controller
        run: |
          iverilog -o ctrl -g2005-sv src/ctrl.sv tests/ctrl_tb.sv
          vvp ctrl

      - name: Register file
        run: |
          iverilog -o rf -g2005-sv src/rf.sv tests/rf_tb.sv
          vvp rf

      - name: ram
        run: |
          iverilog -o ram -g2005-sv src/ram.sv tests/ram_tb.sv
          vvp ram

      - name: cpu
        run: |
          iverilog -o cpu -g2005-sv src/cpu.sv tests/cpu_tb.sv
          vvp cpu
