name: Cpu test

on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Install Verilator Action
        uses: V0XNIHILI/install-verilator-action@v0.0.2

      - name: Test ALU
        run: verilator -cc src/alu.sv --exe tests/alu_tb.sv

      #- name: Test Controller
      #  run: verilator --timing -cc src/ctrl.sv --exe tests/ctrl_tb.sv

      #- name: Test Register file
      #  run: verilator --timing -cc src/rf.sv --exe tests/rf_tb.sv

      #- name: Test RAM
      #  run: verilator --timing -cc src/ram.sv --exe tests/ram_tb.sv

      #- name: Test CPU
      #  run: verilator --timing -cc src/cpu.sv --exe tests/cpu_tb.sv
