name: Cpu test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Verilator Action
        uses: V0XNIHILI/install-verilator-action@v0.0.2

      - name: Checkout code
        use: actions/checkout@v3

      - name: Test alu
        run: verilator --timing -cc ./src/alu.sv --exe ./tests/alu_tb.sv

  #test:
  #  runs-on: ubuntu-latest
  #  needs: build

  #  strategy:
  #    matrix:
  #      target: [alu]
  #      #target: [alu, ctrl, rf, ram, cpu]

  #  steps:
  #    - name: Test ${{ matrix.target }}
  #      run: verilator --timing -cc src/${{ matrix.target}}.sv --exe tests/${{ matrix.target }}_tb.sv
