name: Cpu test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Icarus Verilog
        run: |
          sudo apt-get update
          sudo apt-get install -y iverilog

      - name: Build ALU
        run: |
          iverilog -o alu -g2005-sv src/alu.sv tests/alu_tb.sv

      - name: Build Controller
        run: |
          iverilog -o ctrl -g2005-sv src/ctrl.sv tests/ctrl_tb.sv

      # - name: Build Register file
      #   run: |
      #     iverilog -o rf -g2005-sv src/rf.sv tests/rf_tb.sv

      # - name: Build RAM
      #   run: |
      #     iverilog -o ram -g2005-sv src/ram.sv tests/ram_tb.sv

      # - name: Build CPU
      #   run: |
      #     iverilog -o cpu -g2005-sv src/cpu.sv tests/cpu_tb.sv

  test:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Test ALU
        run: |
          vvp -N alu

      - name: Test Controller
        run: |
          vvp -N ctrl

      # - name: Test Register file
      #   run: |
      #     vvp -N rf

      # - name: Test RAM
      #   run: |
      #     vvp -N ram

      # - name: Test CPU
      #   run: |
      #     vvp -N cpu

