name: Cpu test

on:
  push:
    branches:
      - '**'  # Run on push events for all branches

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [alu, ctrl]
        #target: [alu, ctrl, rf, ram, cpu]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Verilator Action
      uses: V0XNIHILI/install-verilator-action@v0.0.2

    - name: Test ${{ matrix.target }}
      continue-on-error: true
      run: | 
        verilator --timing -Wall --trace -cc src/${{ matrix.target}}.sv --exe tests/${{ matrix.target }}_tb.sv --binary && ./obj_dir/V${{ matrix.target}}
    - name: Test 2 ${{ matrix.target }}
      continue-on-error: true
      run: | 
        verilator --timing -Wall --trace --cc tests/${{ matrix.target }}_tb.sv src/${{ matrix.target }}.sv && make -j -C obj_dir -f V${{ matrix.target }}.mk V${{ matrix.target }} && ./obj_dir/V${{ matrix.target}}

