name: Cpu test

on:
  push:
    branches:
      - '**'  # Run on push events for all branches

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Verilator Action
      uses: V0XNIHILI/install-verilator-action@v0.0.2

    - name: Test alu
      run: | 
        verilator --timing --timescale 10ns/1ns --clk --build --assert -Wall --trace -cc  --binary --exe src/alu.sv tests/alu_tb.sv  
        && ./obj_dir/Valu

    - name: Test ctrl
      run: | 
         verilator --timing  --timescale 10ns/1ns --clk --build --assert -Wall --trace -cc  --binary --exe  src/alu.sv src/ctrl.sv tests/ctrl_tb.sv 
         && ./obj_dir/Vctrl
