name: Cpu test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [alu, ctrl]
        #target: [alu, ctrl, rf, ram, cpu]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Verilator Action
      uses: V0XNIHILI/install-verilator-action@v0.0.2

    - name: Test ${{ matrix.target }}
      run: | 
        verilator --timing -cc src/${{ matrix.target}}.sv --exe tests/${{ matrix.target }}_tb.sv --binary 
        cd obj_dir
        ./V${{ matrix.target}}
