name: Cpu test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Verilator Action
        uses: V0XNIHILI/install-verilator-action@v0.0.2
      - name: post build
        run: which verilator

  test:
    runs-on: ubuntu-latest
    needs: build

    strategy:
      matrix:
        target: [alu]
        #target: [alu, ctrl, rf, ram, cpu]

    steps:
      - name: Test ${{ matrix.target }}
        run: verilator --timing -cc src/${{ matrix.target}}.sv --exe tests/${{ matrix.target }}_tb.sv
